<?php
//?Aqui se ponen los links de cada elemento y se cargan automaticamente en el sidebar
$Dashboard='../templates/Dashboard.php';
$Task_Assignment='';
$Pcbs_Location='../templates/Pcbs_location.php';
$Calendar_Events='../templates/Calendar_Events.php';
$Know_Issues='../templates/Known_Issues.php';
$ICT='';
$Fixtures_for_Models='';
$ICS='';
$Mantenaince='../templates/ICT_Mantenaince.php';
$Program_Backups='';
$Pass_Rate='../templates/Pass-Rate.php';
$SPI_AOI='';
$Undefined_Item='';
$Departament='';
$Equipment_Information='';
$Equipment_Inventory='../templates/Equipment_Inventory.php';
$User='';
$Add_User='../templates/Add_User.php';
$Edit_User='../templates/Edit_User.php';
$iFrame='../templates/iFrame.php';
$Documentation='';
$Help='';
$Logout='';
?>