<?php
$Dashboard='../templates/Dashboard.php';
$Task_Assignment='';
$Storage='';
$Pcbs_Location='';
$Calendar_Events='';
$Know_Issues='../templates/Known_Issues.php';
$ICT='';
$Fixtures_for_Models='';
$ICS='';
$Mantenaince='';
$Program_Backups='';
$Pass_Rate='';
$SPI_AOI='';
$Undefined_Item='';
$Departament='';
$Equipment_Information='';
$Equipment_Inventory='';
$User='';
$Add_User='';
$Edit_User='';
$iFrame='';
$Documentation='';
$Help='';
$Logout='';
?>